#!/usr/bin/env python3

import jinja2;
import os;


if __name__ == "__main__":
    file=open("generated.h.tmpl", "r");
    content = file.read();

    template = jinja2.Template(content);

    vals = {"type":"float", "name":"float32"};
    result = template.render(item = vals);
    w_file = open("generated.h", "w");
    w_file.write(result);

    pass
