#!/usr/bin/env python3

import argparse;
import json;


def parse_args():
    default_type_file_location="./types.json";
    default_template_folder="./";

    parser = argparse.ArgumentParser(description = 'Parse arguments for C source file generation from json data');
    parser.add_argument('--file', help='file location', default=default_type_file_location);
    parser.add_argument('--template', help='template for the code generation', default=default_template_folder);
    args = parser.parse_args();

    return [args.file, args.template];

def parse_json_file(json_file_location):
    json_file = open(json_file_location, "r");
    json_string = json_file.read();
    json_file.close();

    json_obj = json.loads(json_string);
    return json_obj;

if __name__ == "__main__":
    [file_location, template_folder] = parse_args();
    json_obj = parse_json_file(file_location);

    print(json_obj);

    pass
