#!/usr/bin/env python3

import argparse;
import json;

import c_bindings;


def parse_args():
    default_type_file_location="./types.json";
    default_template_folder="./";

    parser = argparse.ArgumentParser(description = 'Parse arguments for C source file generation from json data');
    parser.add_argument('--root', help='root dir', default="./");
    parser.add_argument('--file', help='file location', default=default_type_file_location);
    parser.add_argument('--template', help='template for the code generation', default=default_template_folder);
    args = parser.parse_args();

    return [args.file, args.template, args.root];

def parse_json_file(json_file_location):
    json_file = open(json_file_location, "r");
    json_string = json_file.read();
    json_file.close();

    json_obj = json.loads(json_string);
    return json_obj;

if __name__ == "__main__":
    [file_location, template_folder, root_dir] = parse_args();
    json_obj = parse_json_file(root_dir + file_location);

    var_map = {};

    var_map["TYPES"] = [];

    for type_var in json_obj["types"]:
        var_map["TYPES"].append(type_var["type"])

    var_map["OUTPUT_NAME"] = json_obj["output_name"];

    c_bindings.generate(root_dir + template_folder, var_map);

    pass
